feat: extend database logger context
cycle/database pull request #165
Opened 2024-03-19 18:32 UTC by lotyp

## Changes

- Introduced additional options in DriverConfig for detailed logging control: `logInterpolatedQueries`. Converts query into interpolated one. (Before change, this was done using `logQueryParameters`
- `logQueryParameters` - Now, does, what variable name says — Logs query parameters as array

- Modified statement method in Driver.php to utilize new logging options, enriching log context with driver details, execution time, row count, and query parameters.

## Rationale
These changes aim to improve the ORM's debugging and monitoring capabilities by offering detailed and configurable logging insights.

## Checklist

2024-03-21 13:35 UTC, lotyp commented on src/Query/Interpolator.php
>      }
Probably psalm typings are needed here

2024-03-21 13:36 UTC, lotyp commented on src/Query/Interpolator.php
> +     * @return array An associative array with keys 'named' and 'unnamed'.
Probably psalm typings are needed here, to define that array has two keys: 'named', 'unnamed'. Or rollback this change to initial.

2024-03-26 08:35 UTC, msmakouz requested changes

2024-03-26 08:35 UTC, msmakouz commented on src/Driver/Driver.php
> +    protected function defineLoggerContext(float $queryStart, PDOStatement|PDOStatementInterface|null $statement, ?iterable $parameters): array
I think we can use the `iterable` type for **$parameters** with a default value of an empty array. Since you pass parameters to this method with logging enabled (and they cannot be null, according to the typing of the `statement` method), or an empty array. Also, on line **703**, you use a foreach loop without checking **$parameters** for **null** before it: 
```suggestion
    protected function defineLoggerContext(
        float $queryStart, 
        PDOStatement|PDOStatementInterface|null $statement, 
        iterable $parameters = []
    ): array
```

2024-03-26 08:35 UTC, msmakouz commented on src/Query/Interpolator.php
> +     * @return array An associative array with keys 'named' and 'unnamed'.
Yes, I agree with you. According to the code, there can only be two keys in the array, I would specify them in Psalm's types.

2024-03-27 00:43 UTC, lotyp commented on src/Driver/Driver.php
> +    protected function defineLoggerContext(float $queryStart, PDOStatement|PDOStatementInterface|null $statement, ?iterable $parameters): array
I've updated the method to default $parameters to an empty array and removed the nullable type hint, making it always iterable. This change allows us to skip the null check before the foreach loop, streamlining the code as per your suggestion.

2024-03-27 05:54 UTC, roxblnfk approved these changes
LGTM

2024-03-27 08:35 UTC, msmakouz approved these changes

2024-03-27 09:48 UTC, merged